#!/usr/bin/env python3
"""Flatten an annotated DISHTINY genome JSON into a CSV, one row per site.

The JSON that DISHTINY dumps for a specimen carries, for each instruction, its
operation name, its three raw argument bytes, its 64-bit tag, and a list of
human-readable ``descriptors`` generated by the operation's own
``descriptors()`` method.  This script lifts every descriptor key into its own
column so that the genome can be tabulated directly from a committed data file.

Module numbers are assigned by scanning for ``Global Anchor`` instructions,
each of which registers the tag that makes the following run of instructions
addressable; module ``n`` spans from the ``n``-th anchor up to, but excluding,
the next one.  ``Nop-0`` does not open a module: despite its name sharing a
prefix with the nop substituted by single-site knockouts, every ``Nop``
performs no operation.

One column is derived rather than copied: ``target_label`` joins a state
target with its index.  Every other column is copied verbatim out of the JSON.

The output is tab-separated (no field contains a tab or a quote) rather than
comma-separated, because csvsimple-l3, which the LaTeX table reads it with
(``respect all``), does not understand RFC 4180 quoting of fields that contain
commas, and instruction semantics such as ``if a, terminate core`` do.

Usage:
    ./make_annotated_genome_table.py <genome.json> <out.tsv>
"""

import csv
import json
import sys

# descriptor keys this script knows how to place
KNOWN_DESCRIPTORS = [
    "summary",
    "argument a",
    "argument b",
    "argument c",
    "value",
    "probability",
    "target",
    "target index",
    "target jump table",
    "tag moniker",
    "tag bits",
]

COLUMNS = [
    "site",
    "module",
    "module_offset",
    "module_size",
    "operation",
    "summary",
    "arg_a",
    "arg_b",
    "arg_c",
    "value",
    "probability",
    "target",
    "target_index",
    "target_label",
    "target_jump_table",
    "tag_moniker",
    "tag_bits",
]


def load_program(path):
    with open(path) as handle:
        return json.load(handle)["value0"]["program"]


def module_bounds(program):
    """Return one (module_index, module_start, module_end) triple per site."""
    anchors = [
        idx for idx, inst in enumerate(program) if inst["operation"] == "Global Anchor"
    ]

    out = []
    for site in range(len(program)):
        preceding = [anchor for anchor in anchors if anchor <= site]
        if not preceding:
            out.append((None, None, None))
            continue
        module = len(preceding) - 1
        start = anchors[module]
        end = anchors[module + 1] if module + 1 < len(anchors) else len(program)
        out.append((module, start, end))

    return out


def main():
    try:
        __, genome_path, tsv_path = sys.argv
    except ValueError:
        print(__doc__)
        sys.exit(1)

    program = load_program(genome_path)
    bounds = module_bounds(program)

    with open(tsv_path, "w", newline="") as handle:
        writer = csv.DictWriter(
            handle, fieldnames=COLUMNS, delimiter="\t", lineterminator="\n"
        )
        writer.writeheader()

        for site, inst in enumerate(program):
            descriptors = {
                entry["key"]: entry["value"] for entry in inst["descriptors"]
            }
            module, start, end = bounds[site]
            args = inst["args"]

            summary = descriptors.get("summary", "")
            target = descriptors.get("target", "").replace("dish2::", "")
            target_index = descriptors.get("target index", "")

            row = {
                "site": site,
                "module": "" if module is None else module,
                "module_offset": "" if start is None else site - start,
                "module_size": "" if start is None else end - start,
                "operation": inst["operation"],
                "summary": summary,
                "arg_a": args.get("value0", ""),
                "arg_b": args.get("value1", ""),
                "arg_c": args.get("value2", ""),
                "value": descriptors.get("value", ""),
                "probability": descriptors.get("probability", ""),
                "target": target,
                "target_index": target_index,
                "target_label": (f"{target}[{target_index}]" if target else ""),
                "target_jump_table": descriptors.get("target jump table", ""),
                "tag_moniker": descriptors.get("tag moniker", ""),
                "tag_bits": descriptors.get("tag bits", ""),
            }
            writer.writerow(row)

    unplaced = {
        key
        for inst in program
        for key in (entry["key"] for entry in inst["descriptors"])
        if key not in KNOWN_DESCRIPTORS
    }
    if unplaced:
        print(f"warning: descriptor keys without a column: {sorted(unplaced)}")

    print(f"wrote {len(program)} sites to {tsv_path}")


if __name__ == "__main__":
    main()
