#!/usr/bin/env python3
"""Flatten an annotated DISHTINY genome JSON into a CSV, one row per site.

The JSON that DISHTINY dumps for a specimen carries, for each instruction, its
operation name, its three raw argument bytes, its 64-bit tag, and a list of
human-readable ``descriptors`` generated by the operation's own
``descriptors()`` method.  This script lifts every descriptor key into its own
column so that the genome can be tabulated directly from a committed data file.

Module numbers are assigned by scanning for ``Global Anchor`` instructions,
each of which registers the tag that makes the following run of instructions
addressable; module ``n`` spans from the ``n``-th anchor up to, but excluding,
the next one.  ``Nop-0`` does not open a module: despite its name sharing a
prefix with the nop substituted by single-site knockouts, every ``Nop``
performs no operation.

One column is derived rather than copied: ``target_label`` joins a state
target with its index.  Every other column is copied verbatim out of the JSON.

Requires pandas.

The output is tab-separated (no field contains a tab or a quote) rather than
comma-separated, because csvsimple-l3, which the LaTeX table reads it with
(``respect all``), does not understand RFC 4180 quoting of fields that contain
commas, and instruction semantics such as ``if a, terminate core`` do.

Usage:
    ./make_annotated_genome_table.py <genome.json> <out.tsv>
"""

import json
import sys

import pandas as pd

COLUMNS = [
    "site",
    "module",
    "module_offset",
    "module_size",
    "operation",
    "summary",
    "arg_a",
    "arg_b",
    "arg_c",
    "value",
    "probability",
    "target",
    "target_index",
    "target_label",
    "target_jump_table",
    "tag_moniker",
    "tag_bits",
]

DESCRIPTORS = {
    "summary": "summary",
    "value": "value",
    "probability": "probability",
    "target": "target",
    "target index": "target_index",
    "target jump table": "target_jump_table",
    "tag moniker": "tag_moniker",
    "tag bits": "tag_bits",
}

# register-argument descriptors are redundant with the raw args
IGNORED_DESCRIPTORS = {"argument a", "argument b", "argument c"}


def main():
    try:
        __, genome_path, tsv_path = sys.argv
    except ValueError:
        print(__doc__)
        sys.exit(1)

    with open(genome_path) as handle:
        program = json.load(handle)["value0"]["program"]

    descriptors = pd.DataFrame(
        {entry["key"]: entry["value"] for entry in inst["descriptors"]}
        for inst in program
    )
    unplaced = set(descriptors) - set(DESCRIPTORS) - IGNORED_DESCRIPTORS
    if unplaced:
        print(f"warning: descriptor keys without a column: {sorted(unplaced)}")

    df = pd.DataFrame(
        {
            "site": range(len(program)),
            "operation": [inst["operation"] for inst in program],
            "arg_a": [inst["args"]["value0"] for inst in program],
            "arg_b": [inst["args"]["value1"] for inst in program],
            "arg_c": [inst["args"]["value2"] for inst in program],
        }
    ).join(descriptors.rename(columns=DESCRIPTORS))

    is_anchor = df["operation"] == "Global Anchor"
    module = is_anchor.cumsum() - 1
    df["module"] = module.where(module >= 0)
    df["module_offset"] = df["site"] - df["site"].where(is_anchor).ffill()
    df["module_size"] = df.groupby("module")["site"].transform("size")
    df["target"] = df["target"].str.replace("dish2::", "", regex=False)
    df["target_label"] = (df["target"] + "[" + df["target_index"] + "]").where(
        df["target"].notna()
    )

    df = df.astype({c: "Int64" for c in ("module", "module_offset", "module_size")})
    df[COLUMNS].to_csv(tsv_path, sep="\t", index=False, lineterminator="\n")

    print(f"wrote {len(df)} sites to {tsv_path}")


if __name__ == "__main__":
    main()
