#!/usr/bin/env python3
"""Flatten an annotated DISHTINY genome JSON into a TSV, one row per site.

The JSON that DISHTINY dumps for a specimen carries, for each instruction, its
operation name, its three raw argument bytes, its 64-bit tag, and a list of
human-readable ``descriptors`` generated by the operation's own
``descriptors()`` method.  This script lifts every descriptor key into its own
column so that the genome can be tabulated directly from a committed data file.

Module boundaries follow signalgp-lite's ``GlobalAnchorIterator``: the first
module starts at site 0, and each later module starts at the first
``Global Anchor`` that comes after at least one ``Local Anchor`` since the
previous module started.  A ``Global Anchor`` with no ``Local Anchor`` since the
last module start therefore does not open a module.

One column is derived rather than copied: ``target_label`` joins a state
target with its index.  Every other column is copied out of the JSON.

Requires pandas.  Run from the repository root with no arguments.

The output is tab-separated (no field contains a tab or a quote) rather than
comma-separated, because csvsimple does not understand RFC 4180 quoting of
fields that contain commas, and instruction semantics such as ``if a, terminate
core`` do.  Text fields are written already TeX-escaped (``a = b & c`` becomes
``a = b \\& c``), because instruction semantics contain ``%``, ``&``, ``~``,
``^`` and ``|``, which a LaTeX table cannot read safely out of a data file
otherwise.
"""

import json

import pandas as pd

GENOME_PATH = "data/genome-16005-stint100-highestroot.json"
TSV_PATH = "data/annotated-genome-16005-stint100-highestroot.tsv"

TEX_ESCAPES = str.maketrans(
    {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
        "|": r"\textbar{}",
    }
)

COLUMNS = [
    "site",
    "module",
    "module_offset",
    "module_size",
    "operation",
    "summary",
    "arg_a",
    "arg_b",
    "arg_c",
    "value",
    "probability",
    "target",
    "target_index",
    "target_label",
    "target_jump_table",
    "tag_moniker",
    "tag_bits",
]


def main():
    with open(GENOME_PATH) as handle:
        program = json.load(handle)["value0"]["program"]

    descriptors = pd.DataFrame(
        {entry["key"]: entry["value"] for entry in inst["descriptors"]}
        for inst in program
    )
    descriptors.columns = descriptors.columns.str.replace(" ", "_")
    unplaced = set(descriptors) - set(COLUMNS)
    if unplaced:
        print(f"warning: descriptor keys without a column: {sorted(unplaced)}")

    df = pd.DataFrame(
        {
            "site": range(len(program)),
            "operation": [inst["operation"] for inst in program],
            "arg_a": [inst["args"]["value0"] for inst in program],
            "arg_b": [inst["args"]["value1"] for inst in program],
            "arg_c": [inst["args"]["value2"] for inst in program],
        }
    ).join(descriptors)

    modules, module_start, has_local = [], [], False
    for site, operation in enumerate(df["operation"]):
        if site == 0 or (operation == "Global Anchor" and has_local):
            module_start.append(site)
            has_local = False
        has_local |= operation == "Local Anchor"
        modules.append(len(module_start) - 1)
    df["module"] = modules
    df["module_offset"] = df["site"] - df["module"].map(module_start.__getitem__)
    df["module_size"] = df.groupby("module")["site"].transform("size")
    df["target"] = df["target"].str.replace("dish2::", "", regex=False)
    df["target_label"] = (df["target"] + "[" + df["target_index"] + "]").where(
        df["target"].notna()
    )

    text = df.select_dtypes(exclude="number").columns
    df[text] = df[text].apply(lambda col: col.str.translate(TEX_ESCAPES))
    df.reindex(columns=COLUMNS).to_csv(
        TSV_PATH, sep="\t", index=False, lineterminator="\n"
    )

    print(f"wrote {len(df)} sites to {TSV_PATH}")


if __name__ == "__main__":
    main()
